language: node_js
node_js:
  - '12'
cache:
  directories:
    - node_modules
install:
  - npm i -g travis-ci-cloudfront-invalidation
  - npm install
before_script:
  - npm run validate
script:
  - npm run build
  - npm run copy:assets
deploy:
  provider: s3
  edge: true
  access_key_id: $AWS_ACCESS_KEY_ID
  secret_access_key: $AWS_SECRET_ACCESS_KEY
  bucket: $S3_BUCKET
  local_dir: dist
  on:
    branch: master
# Uncomment this when getting to distributions
# after_deploy:
#   - travis-ci-cloudfront-invalidation -a $AWS_ACCESS_KEY_ID -s
#     $AWS_SECRET_ACCESS_KEY -c $CLOUDFRONT_ID -i '/*' -b $TRAVIS_BRANCH -p
#     $TRAVIS_PULL_REQUEST
